name: Scheduled Temperature Stats

on:
  schedule:
    # Every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  run-temp-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0           # Fetch full history for pushes
          persist-credentials: true # So the checkout action can push

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run temperature stats script
        run: python temps_stats.py

      - name: Commit JSON output
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add temp_*.json
          # Only commit if there are changes
          git diff --cached --quiet || git commit -m "Update temperature stats JSON"
          git push
